spring:
  application:
    name: sample-service
  cloud:
    discovery:
      enabled: true

server:
  port: ${app.port}

app:
  id: ${random.uuid}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${app.eureka-url}
