spring:
  application:
    name: feign-service
  cloud:
    discovery:
      enabled: true

server:
  port: ${app.port}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${app.eureka-url}
